### ISSUE TITLE
nopt dependency

### ISSUE THREAD

**Issue by larshp** [isaacs/node-touch#33]
Hi,
It looks like the code using `nopt` was removed in https://github.com/isaacs/node-touch/commit/3e06ea9fc5d6bfe52a661bfffef4c1d793dd4574

However, its still listed as a dependency, https://www.npmjs.com/package/touch?activeTab=dependencies, and `nopt` uses `abbrev`, so two extra dependencies are installed

I guess `nopt` can be removed from https://github.com/isaacs/node-touch/blob/master/package.json ?

**Comment by tedwash** [comment]
Just stumbled upon this due to `nopt@1.10.0` caused some strange error with the hash not matching when downloading this library in our Bazel build. Any chance we can get a patch version that removes the unused dependency?
