### ISSUE TITLE
Error when touching directories

### ISSUE THREAD

**Issue by mstade** [isaacs/node-touch#8]
``` sh
$ touch node_modules/
bad touch!
/Users/mstade/dev/websdk/nap/node_modules/touch/bin/touch.js:28
      throw er
      ^

Error: EISDIR: illegal operation on a directory, open 'node_modules/'
    at Error (native)
```

Quite possibly out of scope for the module, but figured I'd report it either way.

---

I don't use this module myself, but ran into a problem with builds suddenly failing because of it. The reason is during the build, the `$PATH` variable is prepended with `node_modules/.bin`, so local executables can be conveniently used in the Makefile. Because it's prepended, `touch` takes precedence over the system `touch`, and because this module doesn't work with directories the build failed.

The builds started suddenly failing, because Travis CI started including Node 5.0 in their environment setup. This includes npm 3, which has the new flat module layout. This brought up the this module from the node_modules depths, and voila – failing builds.

Interesting little detour. :o)

It was easy enough to fix. Just changed it to append `node_modules/.bin` to `$PATH`, as opposed to prepending it:

``` makefile
PATH := $(PATH):node_modules/.bin
```

Someone else might run into the same issue, so hopefully searching will lead them here.

**Comment by isaacs** [comment]
Since `touch(1)` ignores dirs, this module ought to swallow `EISDIR` errors.

**Comment by isaacs** [comment]
(that is, yes, this is a bug, thank you for the report, patch welcome with test!)

**Comment by mstade** [comment]
I don't think `touch(1)` ignores directories, does it? At least, I just tried it and it seems to work:

```sh
$ ls -l
total 0
drwxr-xr-x 2 mstade wheel 68 Nov  4 20:07 foo/

$ touch foo

$ ls -l
total 0
drwxr-xr-x 2 mstade wheel 68 Nov  4 20:09 foo/
```

**Comment by isaacs** [comment]
Ah!  you're right.  It doesn't ignore dirs, it updates their times properly.  (What I should've said is, it swallows the `EISDIR` when it tries to open the filename with O_CREAT, and uses `utimes` instead of `futimes`.)

```
$ mkdir foo; touch -t 198001010000 foo; ls -laF | grep foo
drwxr-xr-x   2 isaacs  staff     68 Jan  1  1980 foo/
```

**Comment by mstade** [comment]
Right on. :o)

I'll try to find a minute to fix this. If nothing else because what worked to fix my build *locally* still doesn't work on Travis, for whatever reason. Thanks for the feedback chief!

**Comment by wereHamster** [comment]
Another workaround is to run touch with `--force --nocreat` (or `-fc`).

Explanation: The exception is thrown by `fs.open()`, but only if flags contain `O_RDWR` or `O_CREAT` (but see note below). `O_RDWR` is set when the `force` option is OFF, `O_CREAT` is set when the `nocreate` option is OFF. Enable both options and it will work on directories.

Why does force=OFF imply `O_RDWR`? I don't know. The source code has comments and git history doesn't reveal anything useful either. I looked at the source of coreutils, openbsd touch and the touch utility in Mac OS X, and neither of those use `O_RDWR`.

Note: Behavior of `fs.open(pathToDirectory, O_CREAT)` is different on Mac OS X (El Capitan) and Linux (Ubuntu 14.04.4 LTS): On Mac OS X it works, whereas on Linux it throws the EISDIR error.

**Comment by nylen** [comment]
I keep seeing this issue pop up.  It should be fixed here, yes, but where are the instructions to set `$PATH` like this?

```sh
export PATH=./node_modules/.bin:$PATH
```

`$PATH` should not vary based on the current directory, or at least this should come at the end of the path; if you do that, you're just asking for issues with something overriding a system command.

**Comment by kwight** [comment]
After having set that `export` from the `nvm` [instructions](https://www.npmjs.com/package/nvm) at some point, I ran into the "bad touch!" error. Swapping it  to the end corrected it.

`export PATH=$PATH:./node_modules/.bin`

**Comment by mstade** [comment]
@nylen that's exactly what my resolution was in the original post. I don't know why the `./node_modules/.bin` was prepended, but changing it to be appended fixed it obviously. Just now saw #14 to fix this, thanks a lot for putting in the effort!
